### PR TITLE
[rust] option: finish implementing; fix everything broken

### LINKED ISSUE #1693: [Rust] Improve Concept Exercise: options
This issue describes how to improve the `options` concept exercise for the Rust track.

## Getting started

**Please please please read the docs before starting.** Posting PRs without reading these docs will be a lot more frustrating for you during the review cycle, and exhaust Exercism's maintainers' time. So, before creating the issue, please read up on the following documents:

- [The features of v3](https://github.com/exercism/v3/blob/master/docs/concept-exercises.md).
- [Rationale for v3](https://github.com/exercism/v3/blob/master/docs/rationale-for-v3.md).
- [What are concept exercise and how they are structured?](https://github.com/exercism/v3/blob/master/docs/features-of-v3.md)

Please also watch the following video:

- [The Anatomy of a Concept Exercise](https://www.youtube.com/watch?v=gkbBqd7hPrA).

## Goal

Address @coriolinus 's remaining feedback for #1603. I define this as unresolved comments.

## Help

If you have any questions while improving the exercise, please post the questions as comments in this issue.

### PR DESCRIPTION
**Pull request by coriolinus**
https://github.com/exercism/v3/pull/1603 was merged incomplete and broken
under the optimistic merging strategy. This PR finishes and fixes it.

Closes #1693.

### CODE REVIEW

File: languages/rust/exercises/concept/options/tests/options.rs [hunk 1]
```diff
@@ -2,85 +2,92 @@ use options::*;
...
 #[ignore]
 fn test_reviving_alive_player() {
-    let level: u32 = 8;
     let alive_player = Player {
         health: 1,
         mana: None,
-        level,
+        level: 8,
     };
     assert_eq!(alive_player.revive().is_none(), true);
```
Comment (petertseng) [inline languages/rust/exercises/concept/options/tests/options.rs:26]: Perhaps `assert_eq!(alive_player.revive(), None)` or  `assert!(alive_player.revive().is_none())` ? Probably the former because I think it'd give a more useful result by telling what `Some` was returned, but I guess it doesn't really matter.

File: languages/rust/exercises/concept/options/tests/options.rs [hunk 2]
```diff
@@ -2,85 +2,92 @@ use options::*;
...
+        mana: Some(2),
+        level: 22,
+    };
+
+    // we want to clone so we can compare before-and-after effects of casting the spell,
+    // but we don't want to introduce that concept to the student yet, so we have to do it manually
+    let clone = Player {
+        health: no_mana_wizard.health,
+        mana: no_mana_wizard.mana,
+        level: no_mana_wizard.level,
```
Comment (petertseng) [inline languages/rust/exercises/concept/options/tests/options.rs:63]: any chance to use `..no_mana_wizard` here, or is that in fact the concept we don't want to introduce yet?

**Review by petertseng — APPROVED** [review]

File: languages/rust/exercises/concept/options/tests/options.rs [hunk 3]
```diff
@@ -2,85 +2,92 @@ use options::*;
...
     };
```
Comment (coriolinus) [inline languages/rust/exercises/concept/options/tests/options.rs:64]:
```suggestion
    let clone = Player { ..no_mana_wizard };
```

File: languages/rust/exercises/concept/options/tests/options.rs (hunk 1 above)
Comment (coriolinus) [reply languages/rust/exercises/concept/options/tests/options.rs:26]:
```suggestion
    assert_eq!(alive_player.revive(), None);
```

File: languages/rust/exercises/concept/options/tests/options.rs [hunk 4]
```diff
@@ -2,85 +2,88 @@ use options::*;
...
+        health: 87,
         mana: None,
-        level,
+        level: 6,
+    };
+
+    let clone = Player {
+        health: underleveled_player.health,
+        mana: underleveled_player.mana,
+        level: underleveled_player.level,
```
Comment (petertseng) [inline languages/rust/exercises/concept/options/tests/options.rs:82]: and here as well

File: languages/rust/exercises/concept/options/tests/options.rs [hunk 5]
```diff
@@ -2,85 +2,88 @@ use options::*;
...
     };
```
Comment (coriolinus) [inline languages/rust/exercises/concept/options/tests/options.rs:83]:
```suggestion
    let clone = Player { ..underleveled_player };
```

Comment (petertseng) [inline languages/rust/exercises/concept/options/tests/options.rs:83]:
```suggestion
    let clone = Player { ..underleveled_player };
```

I think that's right... does this repo check compilation

Comment (coriolinus) [reply languages/rust/exercises/concept/options/tests/options.rs]: I don't think it checks compilation, no. Still, that's how I'd write it, so I'm going to commit it.

File: languages/rust/exercises/concept/options/tests/options.rs [hunk 6]
```diff
@@ -2,85 +2,84 @@ use options::*;
...
 fn test_reviving_alive_player() {
-    let level: u32 = 8;
     let alive_player = Player {
         health: 1,
         mana: None,
-        level,
+        level: 8,
     };
-    assert_eq!(alive_player.revive().is_none(), true);
+    assert_eq!(alive_player.revive(), None);
```
Comment (petertseng) [inline languages/rust/exercises/concept/options/tests/options.rs:26]: Oh I figured out why it was this way. If you `assert_eq` with `None`, then the student would have to make the Player PartialEq and Debug. Okay, in that case I'm down with:

```suggestion
    assert!(alive_player.revive().is_none());
```

**Review by petertseng — APPROVED** [review]
I tried it and unless I made a mistake in copying, the example now passes the tests without further modification of either

**Comment by coriolinus** [comment]
CI is red but it appears not to be the fault of this PR. @iHiD recommend squash-merging now.

**Comment by petertseng** [comment]
Maybe this script will come in handy in testing this exercise and others

```sh
commit_to_test=c35f74e231efe70fc09cad6353e391531711d6d1
ex_to_test=options

cargo new --lib $ex_to_test
cd $ex_to_test
mkdir tests
curl https://raw.githubusercontent.com/exercism/v3/$commit_to_test/languages/rust/exercises/concept/$ex_to_test/.meta/example.rs > src/lib.rs
curl https://raw.githubusercontent.com/exercism/v3/$commit_to_test/languages/rust/exercises/concept/$ex_to_test/tests/$ex_to_test.rs > tests/$ex_to_test.rs
cargo test && cargo test -- --ignored
```

**Comment by coriolinus** [comment]
I see: merging was blocked not because some checks had failed, but because some were still pending. Merging now.
